"""Initial migration

Revision ID: 1752941c6129
Revises: 
Create Date: 2026-01-18 17:27:08.879354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1752941c6129'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_trajectories',
    sa.Column('global_id', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('path_data', sa.JSON(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('cameras_seen', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('global_id')
    )
    op.create_index(op.f('ix_person_trajectories_global_id'), 'person_trajectories', ['global_id'], unique=False)
    op.create_table('tracking_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('global_id', sa.String(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('bbox_x1', sa.Integer(), nullable=True),
    sa.Column('bbox_y1', sa.Integer(), nullable=True),
    sa.Column('bbox_x2', sa.Integer(), nullable=True),
    sa.Column('bbox_y2', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('map_x', sa.Float(), nullable=True),
    sa.Column('map_y', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_events_camera_id'), 'tracking_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_global_id'), 'tracking_events', ['global_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_id'), 'tracking_events', ['id'], unique=False)
    op.create_index(op.f('ix_tracking_events_time'), 'tracking_events', ['time'], unique=False)
    op.drop_index(op.f('idx_detection_events_camera_confidence'), table_name='detection_events')
    op.drop_index(op.f('idx_detection_events_camera_time'), table_name='detection_events')
    op.drop_index(op.f('idx_detection_events_confidence'), table_name='detection_events')
    op.drop_index(op.f('idx_detection_events_metadata_gin'), table_name='detection_events', postgresql_using='gin')
    op.drop_index(op.f('idx_detection_events_session_time'), table_name='detection_events')
    op.drop_index(op.f('idx_detection_events_timestamp'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_camera_id'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_environment_id'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_session_id'), table_name='detection_events')
    op.drop_table('detection_events')
    op.drop_index(op.f('idx_geometric_metrics_env_camera'), table_name='geometric_metrics_events')
    op.drop_index(op.f('ix_geometric_metrics_events_camera_id'), table_name='geometric_metrics_events')
    op.drop_index(op.f('ix_geometric_metrics_events_environment_id'), table_name='geometric_metrics_events')
    op.drop_index(op.f('ix_geometric_metrics_events_event_timestamp'), table_name='geometric_metrics_events')
    op.drop_table('geometric_metrics_events')
    op.drop_index(op.f('idx_analytics_totals_bucket'), table_name='analytics_totals')
    op.drop_index(op.f('idx_analytics_totals_camera_bucket'), table_name='analytics_totals')
    op.drop_index(op.f('idx_analytics_totals_env'), table_name='analytics_totals')
    op.drop_table('analytics_totals')
    op.drop_index(op.f('idx_analytics_uptime_daily_camera'), table_name='analytics_uptime_daily')
    op.drop_index(op.f('idx_analytics_uptime_daily_day_env'), table_name='analytics_uptime_daily')
    op.drop_table('analytics_uptime_daily')
    op.drop_index(op.f('idx_person_identities_active'), table_name='person_identities')
    op.drop_index(op.f('idx_person_identities_embedding_gin'), table_name='person_identities', postgresql_using='gin')
    op.drop_index(op.f('idx_person_identities_environment'), table_name='person_identities')
    op.drop_index(op.f('idx_person_identities_global_id'), table_name='person_identities')
    op.drop_index(op.f('idx_person_identities_last_seen'), table_name='person_identities')
    op.drop_index(op.f('idx_person_identities_last_seen_active'), table_name='person_identities')
    op.drop_index(op.f('ix_person_identities_environment_id'), table_name='person_identities')
    op.drop_index(op.f('ix_person_identities_global_person_id'), table_name='person_identities')
    op.drop_table('person_identities')
    op.drop_index(op.f('idx_session_records_environment'), table_name='session_records')
    op.drop_index(op.f('idx_session_records_environment_status'), table_name='session_records')
    op.drop_index(op.f('idx_session_records_session_id'), table_name='session_records')
    op.drop_index(op.f('idx_session_records_start_time'), table_name='session_records')
    op.drop_index(op.f('idx_session_records_status'), table_name='session_records')
    op.drop_index(op.f('idx_session_records_user'), table_name='session_records')
    op.drop_index(op.f('ix_session_records_environment_id'), table_name='session_records')
    op.drop_index(op.f('ix_session_records_session_id'), table_name='session_records')
    op.drop_index(op.f('ix_session_records_user_id'), table_name='session_records')
    op.drop_table('session_records')
    op.drop_index(op.f('idx_analytics_aggregations_composite'), table_name='analytics_aggregations')
    op.drop_index(op.f('idx_analytics_aggregations_environment'), table_name='analytics_aggregations')
    op.drop_index(op.f('idx_analytics_aggregations_time_bucket'), table_name='analytics_aggregations')
    op.drop_index(op.f('idx_analytics_aggregations_type_camera'), table_name='analytics_aggregations')
    op.drop_index(op.f('ix_analytics_aggregations_camera_id'), table_name='analytics_aggregations')
    op.drop_index(op.f('ix_analytics_aggregations_environment_id'), table_name='analytics_aggregations')
    op.drop_index(op.f('ix_analytics_aggregations_time_bucket'), table_name='analytics_aggregations')
    op.drop_table('analytics_aggregations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_aggregations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('time_bucket', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('aggregation_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('camera_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('environment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('total_persons', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unique_persons', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_persons', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_detections', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_entries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_exits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_transitions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_dwell_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_tracking_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_reid_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('successful_tracks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_tracks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aggregated_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_aggregations_pkey'))
    )
    op.create_index(op.f('ix_analytics_aggregations_time_bucket'), 'analytics_aggregations', ['time_bucket'], unique=False)
    op.create_index(op.f('ix_analytics_aggregations_environment_id'), 'analytics_aggregations', ['environment_id'], unique=False)
    op.create_index(op.f('ix_analytics_aggregations_camera_id'), 'analytics_aggregations', ['camera_id'], unique=False)
    op.create_index(op.f('idx_analytics_aggregations_type_camera'), 'analytics_aggregations', ['aggregation_type', 'camera_id'], unique=False)
    op.create_index(op.f('idx_analytics_aggregations_time_bucket'), 'analytics_aggregations', ['time_bucket'], unique=False)
    op.create_index(op.f('idx_analytics_aggregations_environment'), 'analytics_aggregations', ['environment_id'], unique=False)
    op.create_index(op.f('idx_analytics_aggregations_composite'), 'analytics_aggregations', ['aggregation_type', 'environment_id', 'time_bucket'], unique=False)
    op.create_table('session_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('environment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('camera_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('total_persons_tracked', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_detections', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_events', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_detection_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_reid_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('session_records_pkey'))
    )
    op.create_index(op.f('ix_session_records_user_id'), 'session_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_session_records_session_id'), 'session_records', ['session_id'], unique=True)
    op.create_index(op.f('ix_session_records_environment_id'), 'session_records', ['environment_id'], unique=False)
    op.create_index(op.f('idx_session_records_user'), 'session_records', ['user_id'], unique=False)
    op.create_index(op.f('idx_session_records_status'), 'session_records', ['status'], unique=False)
    op.create_index(op.f('idx_session_records_start_time'), 'session_records', ['start_time'], unique=False)
    op.create_index(op.f('idx_session_records_session_id'), 'session_records', ['session_id'], unique=False)
    op.create_index(op.f('idx_session_records_environment_status'), 'session_records', ['environment_id', 'status', 'start_time'], unique=False)
    op.create_index(op.f('idx_session_records_environment'), 'session_records', ['environment_id'], unique=False)
    op.create_table('person_identities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('global_person_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('first_seen_camera', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_seen_camera', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cameras_seen', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('environment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('primary_embedding', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('total_detections', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tracking_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('identity_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('person_identities_pkey'))
    )
    op.create_index(op.f('ix_person_identities_global_person_id'), 'person_identities', ['global_person_id'], unique=True)
    op.create_index(op.f('ix_person_identities_environment_id'), 'person_identities', ['environment_id'], unique=False)
    op.create_index(op.f('idx_person_identities_last_seen_active'), 'person_identities', ['last_seen_at', 'is_active'], unique=False)
    op.create_index(op.f('idx_person_identities_last_seen'), 'person_identities', ['last_seen_at'], unique=False)
    op.create_index(op.f('idx_person_identities_global_id'), 'person_identities', ['global_person_id'], unique=False)
    op.create_index(op.f('idx_person_identities_environment'), 'person_identities', ['environment_id'], unique=False)
    op.create_index(op.f('idx_person_identities_embedding_gin'), 'person_identities', ['primary_embedding'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_person_identities_active'), 'person_identities', ['is_active'], unique=False)
    op.create_table('analytics_uptime_daily',
    sa.Column('day', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('environment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('camera_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('uptime_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('samples', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('day', 'environment_id', 'camera_id', name=op.f('analytics_uptime_daily_pkey'))
    )
    op.create_index(op.f('idx_analytics_uptime_daily_day_env'), 'analytics_uptime_daily', ['day', 'environment_id'], unique=False)
    op.create_index(op.f('idx_analytics_uptime_daily_camera'), 'analytics_uptime_daily', ['camera_id'], unique=False)
    op.create_table('analytics_totals',
    sa.Column('bucket_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('bucket_size_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('environment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('camera_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('detections', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('unique_entities', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('confidence_sum', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confidence_samples', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('uptime_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('bucket_start', 'bucket_size_seconds', 'environment_id', 'camera_id', name=op.f('analytics_totals_pkey'))
    )
    op.create_index(op.f('idx_analytics_totals_env'), 'analytics_totals', ['environment_id'], unique=False)
    op.create_index(op.f('idx_analytics_totals_camera_bucket'), 'analytics_totals', ['environment_id', 'camera_id', 'bucket_start'], unique=False)
    op.create_index(op.f('idx_analytics_totals_bucket'), 'analytics_totals', ['bucket_start'], unique=False)
    op.create_table('geometric_metrics_events',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('event_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('environment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('camera_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('extraction_total_attempts', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('extraction_validation_failures', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('extraction_success_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('transformation_total_attempts', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('transformation_validation_failures', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('transformation_success_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('roi_total_created', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('geometric_metrics_events_pkey'))
    )
    op.create_index(op.f('ix_geometric_metrics_events_event_timestamp'), 'geometric_metrics_events', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_geometric_metrics_events_environment_id'), 'geometric_metrics_events', ['environment_id'], unique=False)
    op.create_index(op.f('ix_geometric_metrics_events_camera_id'), 'geometric_metrics_events', ['camera_id'], unique=False)
    op.create_index(op.f('idx_geometric_metrics_env_camera'), 'geometric_metrics_events', ['environment_id', 'camera_id'], unique=False)
    op.create_table('detection_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('camera_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('environment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('frame_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bbox_x1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('bbox_y1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('bbox_x2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('bbox_y2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('object_class', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tracking_event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('detection_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('detection_events_pkey'))
    )
    op.create_index(op.f('ix_detection_events_session_id'), 'detection_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_detection_events_environment_id'), 'detection_events', ['environment_id'], unique=False)
    op.create_index(op.f('ix_detection_events_camera_id'), 'detection_events', ['camera_id'], unique=False)
    op.create_index(op.f('idx_detection_events_timestamp'), 'detection_events', ['timestamp'], unique=False)
    op.create_index(op.f('idx_detection_events_session_time'), 'detection_events', ['session_id', 'timestamp'], unique=False)
    op.create_index(op.f('idx_detection_events_metadata_gin'), 'detection_events', ['detection_metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_detection_events_confidence'), 'detection_events', ['confidence'], unique=False)
    op.create_index(op.f('idx_detection_events_camera_time'), 'detection_events', ['camera_id', 'timestamp'], unique=False)
    op.create_index(op.f('idx_detection_events_camera_confidence'), 'detection_events', ['camera_id', 'confidence', 'timestamp'], unique=False)
    op.drop_index(op.f('ix_tracking_events_time'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_global_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_camera_id'), table_name='tracking_events')
    op.drop_table('tracking_events')
    op.drop_index(op.f('ix_person_trajectories_global_id'), table_name='person_trajectories')
    op.drop_table('person_trajectories')
    # ### end Alembic commands ###
