"""Initial migration

Revision ID: 4021e4e63a60
Revises: 1752941c6129
Create Date: 2026-01-18 17:33:18.198193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4021e4e63a60'
down_revision: Union[str, Sequence[str], None] = '1752941c6129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_aggregations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aggregation_type', sa.String(length=20), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=True),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('total_persons', sa.Integer(), nullable=True),
    sa.Column('unique_persons', sa.Integer(), nullable=True),
    sa.Column('active_persons', sa.Integer(), nullable=True),
    sa.Column('total_detections', sa.Integer(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('total_entries', sa.Integer(), nullable=True),
    sa.Column('total_exits', sa.Integer(), nullable=True),
    sa.Column('total_transitions', sa.Integer(), nullable=True),
    sa.Column('avg_dwell_time', sa.Float(), nullable=True),
    sa.Column('total_tracking_time', sa.Float(), nullable=True),
    sa.Column('avg_reid_confidence', sa.Float(), nullable=True),
    sa.Column('successful_tracks', sa.Integer(), nullable=True),
    sa.Column('failed_tracks', sa.Integer(), nullable=True),
    sa.Column('aggregated_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'time_bucket')
    )
    op.create_index('idx_analytics_aggregations_composite', 'analytics_aggregations', ['aggregation_type', 'environment_id', 'time_bucket'], unique=False)
    op.create_index('idx_analytics_aggregations_environment', 'analytics_aggregations', ['environment_id'], unique=False)
    op.create_index('idx_analytics_aggregations_time_bucket', 'analytics_aggregations', ['time_bucket'], unique=False)
    op.create_index('idx_analytics_aggregations_type_camera', 'analytics_aggregations', ['aggregation_type', 'camera_id'], unique=False)
    op.create_index(op.f('ix_analytics_aggregations_camera_id'), 'analytics_aggregations', ['camera_id'], unique=False)
    op.create_index(op.f('ix_analytics_aggregations_environment_id'), 'analytics_aggregations', ['environment_id'], unique=False)
    op.create_index(op.f('ix_analytics_aggregations_time_bucket'), 'analytics_aggregations', ['time_bucket'], unique=False)
    op.create_table('analytics_totals',
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bucket_size_seconds', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('detections', sa.BigInteger(), nullable=False),
    sa.Column('unique_entities', sa.BigInteger(), nullable=False),
    sa.Column('confidence_sum', sa.Float(), nullable=False),
    sa.Column('confidence_samples', sa.BigInteger(), nullable=False),
    sa.Column('uptime_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('bucket_start', 'bucket_size_seconds', 'environment_id', 'camera_id')
    )
    op.create_index('idx_analytics_totals_bucket', 'analytics_totals', ['bucket_start'], unique=False)
    op.create_index('idx_analytics_totals_camera_bucket', 'analytics_totals', ['environment_id', 'camera_id', 'bucket_start'], unique=False)
    op.create_index('idx_analytics_totals_env', 'analytics_totals', ['environment_id'], unique=False)
    op.create_table('analytics_uptime_daily',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('uptime_percent', sa.Float(), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('day', 'environment_id', 'camera_id')
    )
    op.create_index('idx_analytics_uptime_daily_camera', 'analytics_uptime_daily', ['camera_id'], unique=False)
    op.create_index('idx_analytics_uptime_daily_day_env', 'analytics_uptime_daily', ['day', 'environment_id'], unique=False)
    op.create_table('detection_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('bbox_x2', sa.Float(), nullable=False),
    sa.Column('bbox_y2', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('object_class', sa.String(length=50), nullable=False),
    sa.Column('tracking_event_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('detection_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', 'timestamp')
    )
    op.create_index('idx_detection_events_camera_time', 'detection_events', ['camera_id', 'timestamp'], unique=False)
    op.create_index('idx_detection_events_confidence', 'detection_events', ['confidence'], unique=False)
    op.create_index('idx_detection_events_session_time', 'detection_events', ['session_id', 'timestamp'], unique=False)
    op.create_index('idx_detection_events_timestamp', 'detection_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_detection_events_camera_id'), 'detection_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_detection_events_environment_id'), 'detection_events', ['environment_id'], unique=False)
    op.create_index(op.f('ix_detection_events_session_id'), 'detection_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_detection_events_tracking_event_id'), 'detection_events', ['tracking_event_id'], unique=False)
    op.create_table('geometric_metrics_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=True),
    sa.Column('extraction_total_attempts', sa.BigInteger(), nullable=False),
    sa.Column('extraction_validation_failures', sa.BigInteger(), nullable=False),
    sa.Column('extraction_success_rate', sa.Float(), nullable=False),
    sa.Column('transformation_total_attempts', sa.BigInteger(), nullable=True),
    sa.Column('transformation_validation_failures', sa.BigInteger(), nullable=True),
    sa.Column('transformation_success_rate', sa.Float(), nullable=True),
    sa.Column('roi_total_created', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_geometric_metrics_env_camera', 'geometric_metrics_events', ['environment_id', 'camera_id'], unique=False)
    op.create_index(op.f('ix_geometric_metrics_events_camera_id'), 'geometric_metrics_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_geometric_metrics_events_environment_id'), 'geometric_metrics_events', ['environment_id'], unique=False)
    op.create_index(op.f('ix_geometric_metrics_events_event_timestamp'), 'geometric_metrics_events', ['event_timestamp'], unique=False)
    op.create_table('person_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('global_person_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_camera', sa.String(length=50), nullable=False),
    sa.Column('last_seen_camera', sa.String(length=50), nullable=False),
    sa.Column('cameras_seen', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('primary_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_detections', sa.Integer(), nullable=True),
    sa.Column('total_tracking_time', sa.Float(), nullable=True),
    sa.Column('identity_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_person_identities_active', 'person_identities', ['is_active'], unique=False)
    op.create_index('idx_person_identities_environment', 'person_identities', ['environment_id'], unique=False)
    op.create_index('idx_person_identities_global_id', 'person_identities', ['global_person_id'], unique=False)
    op.create_index('idx_person_identities_last_seen', 'person_identities', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_person_identities_environment_id'), 'person_identities', ['environment_id'], unique=False)
    op.create_index(op.f('ix_person_identities_global_person_id'), 'person_identities', ['global_person_id'], unique=True)
    op.create_table('person_trajectories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('global_person_id', sa.String(length=100), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('world_x', sa.Float(), nullable=True),
    sa.Column('world_y', sa.Float(), nullable=True),
    sa.Column('velocity_x', sa.Float(), nullable=True),
    sa.Column('velocity_y', sa.Float(), nullable=True),
    sa.Column('acceleration_x', sa.Float(), nullable=True),
    sa.Column('acceleration_y', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('smoothed', sa.Boolean(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('trajectory_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', 'timestamp')
    )
    op.create_index('idx_person_trajectories_camera_time', 'person_trajectories', ['camera_id', 'timestamp'], unique=False)
    op.create_index('idx_person_trajectories_person_time', 'person_trajectories', ['global_person_id', 'timestamp'], unique=False)
    op.create_index('idx_person_trajectories_sequence', 'person_trajectories', ['global_person_id', 'sequence_number'], unique=False)
    op.create_index('idx_person_trajectories_timestamp', 'person_trajectories', ['timestamp'], unique=False)
    op.create_index(op.f('ix_person_trajectories_camera_id'), 'person_trajectories', ['camera_id'], unique=False)
    op.create_index(op.f('ix_person_trajectories_environment_id'), 'person_trajectories', ['environment_id'], unique=False)
    op.create_index(op.f('ix_person_trajectories_global_person_id'), 'person_trajectories', ['global_person_id'], unique=False)
    op.create_index(op.f('ix_person_trajectories_session_id'), 'person_trajectories', ['session_id'], unique=False)
    op.create_table('session_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('camera_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_persons_tracked', sa.Integer(), nullable=True),
    sa.Column('total_detections', sa.Integer(), nullable=True),
    sa.Column('total_events', sa.Integer(), nullable=True),
    sa.Column('avg_detection_confidence', sa.Float(), nullable=True),
    sa.Column('avg_reid_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_records_environment', 'session_records', ['environment_id'], unique=False)
    op.create_index('idx_session_records_session_id', 'session_records', ['session_id'], unique=False)
    op.create_index('idx_session_records_start_time', 'session_records', ['start_time'], unique=False)
    op.create_index('idx_session_records_status', 'session_records', ['status'], unique=False)
    op.create_index('idx_session_records_user', 'session_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_session_records_environment_id'), 'session_records', ['environment_id'], unique=False)
    op.create_index(op.f('ix_session_records_session_id'), 'session_records', ['session_id'], unique=True)
    op.create_index(op.f('ix_session_records_user_id'), 'session_records', ['user_id'], unique=False)
    op.create_table('tracking_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('global_person_id', sa.String(length=100), nullable=False),
    sa.Column('track_id', sa.String(length=100), nullable=True),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('world_x', sa.Float(), nullable=True),
    sa.Column('world_y', sa.Float(), nullable=True),
    sa.Column('bbox_x1', sa.Float(), nullable=True),
    sa.Column('bbox_y1', sa.Float(), nullable=True),
    sa.Column('bbox_x2', sa.Float(), nullable=True),
    sa.Column('bbox_y2', sa.Float(), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('reid_confidence', sa.Float(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', 'timestamp')
    )
    op.create_index('idx_tracking_events_camera_time', 'tracking_events', ['camera_id', 'timestamp'], unique=False)
    op.create_index('idx_tracking_events_env_time', 'tracking_events', ['environment_id', 'timestamp'], unique=False)
    op.create_index('idx_tracking_events_person_time', 'tracking_events', ['global_person_id', 'timestamp'], unique=False)
    op.create_index('idx_tracking_events_session_time', 'tracking_events', ['session_id', 'timestamp'], unique=False)
    op.create_index('idx_tracking_events_timestamp', 'tracking_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_tracking_events_camera_id'), 'tracking_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_environment_id'), 'tracking_events', ['environment_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_global_person_id'), 'tracking_events', ['global_person_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_session_id'), 'tracking_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_track_id'), 'tracking_events', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_events_track_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_session_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_global_person_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_environment_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_camera_id'), table_name='tracking_events')
    op.drop_index('idx_tracking_events_timestamp', table_name='tracking_events')
    op.drop_index('idx_tracking_events_session_time', table_name='tracking_events')
    op.drop_index('idx_tracking_events_person_time', table_name='tracking_events')
    op.drop_index('idx_tracking_events_env_time', table_name='tracking_events')
    op.drop_index('idx_tracking_events_camera_time', table_name='tracking_events')
    op.drop_table('tracking_events')
    op.drop_index(op.f('ix_session_records_user_id'), table_name='session_records')
    op.drop_index(op.f('ix_session_records_session_id'), table_name='session_records')
    op.drop_index(op.f('ix_session_records_environment_id'), table_name='session_records')
    op.drop_index('idx_session_records_user', table_name='session_records')
    op.drop_index('idx_session_records_status', table_name='session_records')
    op.drop_index('idx_session_records_start_time', table_name='session_records')
    op.drop_index('idx_session_records_session_id', table_name='session_records')
    op.drop_index('idx_session_records_environment', table_name='session_records')
    op.drop_table('session_records')
    op.drop_index(op.f('ix_person_trajectories_session_id'), table_name='person_trajectories')
    op.drop_index(op.f('ix_person_trajectories_global_person_id'), table_name='person_trajectories')
    op.drop_index(op.f('ix_person_trajectories_environment_id'), table_name='person_trajectories')
    op.drop_index(op.f('ix_person_trajectories_camera_id'), table_name='person_trajectories')
    op.drop_index('idx_person_trajectories_timestamp', table_name='person_trajectories')
    op.drop_index('idx_person_trajectories_sequence', table_name='person_trajectories')
    op.drop_index('idx_person_trajectories_person_time', table_name='person_trajectories')
    op.drop_index('idx_person_trajectories_camera_time', table_name='person_trajectories')
    op.drop_table('person_trajectories')
    op.drop_index(op.f('ix_person_identities_global_person_id'), table_name='person_identities')
    op.drop_index(op.f('ix_person_identities_environment_id'), table_name='person_identities')
    op.drop_index('idx_person_identities_last_seen', table_name='person_identities')
    op.drop_index('idx_person_identities_global_id', table_name='person_identities')
    op.drop_index('idx_person_identities_environment', table_name='person_identities')
    op.drop_index('idx_person_identities_active', table_name='person_identities')
    op.drop_table('person_identities')
    op.drop_index(op.f('ix_geometric_metrics_events_event_timestamp'), table_name='geometric_metrics_events')
    op.drop_index(op.f('ix_geometric_metrics_events_environment_id'), table_name='geometric_metrics_events')
    op.drop_index(op.f('ix_geometric_metrics_events_camera_id'), table_name='geometric_metrics_events')
    op.drop_index('idx_geometric_metrics_env_camera', table_name='geometric_metrics_events')
    op.drop_table('geometric_metrics_events')
    op.drop_index(op.f('ix_detection_events_tracking_event_id'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_session_id'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_environment_id'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_camera_id'), table_name='detection_events')
    op.drop_index('idx_detection_events_timestamp', table_name='detection_events')
    op.drop_index('idx_detection_events_session_time', table_name='detection_events')
    op.drop_index('idx_detection_events_confidence', table_name='detection_events')
    op.drop_index('idx_detection_events_camera_time', table_name='detection_events')
    op.drop_table('detection_events')
    op.drop_index('idx_analytics_uptime_daily_day_env', table_name='analytics_uptime_daily')
    op.drop_index('idx_analytics_uptime_daily_camera', table_name='analytics_uptime_daily')
    op.drop_table('analytics_uptime_daily')
    op.drop_index('idx_analytics_totals_env', table_name='analytics_totals')
    op.drop_index('idx_analytics_totals_camera_bucket', table_name='analytics_totals')
    op.drop_index('idx_analytics_totals_bucket', table_name='analytics_totals')
    op.drop_table('analytics_totals')
    op.drop_index(op.f('ix_analytics_aggregations_time_bucket'), table_name='analytics_aggregations')
    op.drop_index(op.f('ix_analytics_aggregations_environment_id'), table_name='analytics_aggregations')
    op.drop_index(op.f('ix_analytics_aggregations_camera_id'), table_name='analytics_aggregations')
    op.drop_index('idx_analytics_aggregations_type_camera', table_name='analytics_aggregations')
    op.drop_index('idx_analytics_aggregations_time_bucket', table_name='analytics_aggregations')
    op.drop_index('idx_analytics_aggregations_environment', table_name='analytics_aggregations')
    op.drop_index('idx_analytics_aggregations_composite', table_name='analytics_aggregations')
    op.drop_table('analytics_aggregations')
    # ### end Alembic commands ###
