# Production Configuration for SpotOn Backend
# This file contains production-ready configuration settings

# Application Configuration
app:
  name: "SpotOn Production Backend"
  version: "1.0.0"
  environment: "production"
  debug: false
  log_level: "INFO"
  api_prefix: "/api/v1"

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 30
  keepalive: 2
  max_requests: 1000
  max_requests_jitter: 50

# Database Configuration
database:
  postgres:
    host: "${POSTGRES_HOST}"
    port: "${POSTGRES_PORT:5432}"
    user: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    database: "${POSTGRES_DB}"
    ssl_mode: "require"
    pool_size: 10
    max_overflow: 20
    pool_timeout: 30
    pool_recycle: 3600
    echo: false
  
  timescale:
    host: "${TIMESCALE_HOST}"
    port: "${TIMESCALE_PORT:5432}"
    user: "${TIMESCALE_USER}"
    password: "${TIMESCALE_PASSWORD}"
    database: "${TIMESCALE_DB}"
    ssl_mode: "require"
    pool_size: 5
    max_overflow: 10

# Cache Configuration
cache:
  redis:
    host: "${REDIS_HOST}"
    port: "${REDIS_PORT:6379}"
    db: "${REDIS_DB:0}"
    password: "${REDIS_PASSWORD}"
    ssl: true
    ssl_cert_reqs: "required"
    pool_size: 20
    max_connections: 50
    timeout: 5
    retry_on_timeout: true

# Security Configuration
security:
  jwt:
    secret_key: "${JWT_SECRET_KEY}"
    algorithm: "HS256"
    access_token_expire_minutes: 30
    refresh_token_expire_days: 7
    issuer: "spoton-backend"
    audience: "spoton-frontend"
  
  encryption:
    master_key: "${ENCRYPTION_MASTER_KEY}"
    algorithm: "AES-256-GCM"
    key_rotation_days: 30
    pbkdf2_iterations: 100000
    enable_field_encryption: true
    enable_audit_logging: true
  
  cors:
    allow_origins: ["https://spoton.example.com"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["*"]
    allow_credentials: true
    max_age: 86400

# AI/ML Configuration
ai:
  models:
    detection:
      type: "fasterrcnn"
      weights_path: "/app/models/detection/fasterrcnn_resnet50_fpn.pth"
      confidence_threshold: 0.5
      nms_threshold: 0.5
      device: "cuda"
      half_precision: true
      batch_size: 8
    
    reid:
      type: "clip"
      weights_path: "/app/models/reid/clip_model.pth"
      feature_dim: 512
      similarity_threshold: 0.6
      device: "cuda"
      half_precision: true
      batch_size: 32
    
    tracking:
      type: "botsort"
      max_age: 30
      min_hits: 3
      iou_threshold: 0.3
      association_threshold: 0.5
  
  gpu:
    device: "cuda"
    memory_fraction: 0.8
    allow_growth: true
    mixed_precision: true

# Monitoring Configuration
monitoring:
  metrics:
    enabled: true
    port: 9090
    path: "/metrics"
    include_labels: true
  
  logging:
    level: "INFO"
    format: "json"
    file: "/var/log/spoton/app.log"
    max_size: "100MB"
    backup_count: 5
    rotation: "daily"
  
  health_check:
    enabled: true
    path: "/health"
    interval: 30
    timeout: 10
  
  alerts:
    enabled: true
    webhook_url: "${ALERT_WEBHOOK_URL}"
    cpu_threshold: 80
    memory_threshold: 85
    disk_threshold: 90
    error_rate_threshold: 0.05

# Performance Configuration
performance:
  async_workers: 8
  max_concurrent_requests: 1000
  request_timeout: 30
  websocket_timeout: 300
  cache_ttl: 3600
  compression: true
  gzip_level: 6

# Analytics Configuration
analytics:
  enabled: true
  batch_size: 1000
  processing_interval: 60
  retention_days: 90
  aggregation_intervals: ["1h", "1d", "7d", "30d"]
  real_time_window: 300

# Backup Configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 30
  storage:
    type: "s3"
    bucket: "${BACKUP_S3_BUCKET}"
    access_key: "${BACKUP_S3_ACCESS_KEY}"
    secret_key: "${BACKUP_S3_SECRET_KEY}"
    region: "${BACKUP_S3_REGION}"
    encryption: true

# Resource Limits
resources:
  cpu_limit: "2000m"
  memory_limit: "4Gi"
  gpu_memory_limit: "8Gi"
  disk_limit: "100Gi"
  
  requests:
    cpu: "1000m"
    memory: "2Gi"
    gpu_memory: "4Gi"

# Feature Flags
features:
  real_time_streaming: true
  batch_processing: true
  analytics_dashboard: true
  api_rate_limiting: true
  audit_logging: true
  data_encryption: true
  gdpr_compliance: true
  multi_tenancy: false
  advanced_analytics: true

# Environment-specific Settings
deployment:
  strategy: "rolling"
  max_unavailable: 1
  max_surge: 1
  revision_history_limit: 3
  progress_deadline_seconds: 600
  
  autoscaling:
    enabled: true
    min_replicas: 3
    max_replicas: 10
    target_cpu_utilization: 70
    target_memory_utilization: 80
    scale_up_cooldown: 300
    scale_down_cooldown: 600