name: Python CI

on:
  push:
    branches: [ main, master ] # Adjust if your main branch has a different name
  pull_request:
    branches: [ main, master ] # Adjust if your main branch has a different name

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"] # Matches your pyproject.toml requires-python

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        uv --version # Verify uv installation and PATH

    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv # uv's global cache directory
        key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-${{ matrix.python-version }}-

    - name: Install PyTorch (CPU version)
      run: |
        # Using uv to install PyTorch CPU version.
        # Added --system flag to install into the system Python environment.
        uv pip install --system torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

    - name: Install project dependencies
      run: |
        # Added --system flag here as well.
        uv pip install --system ".[dev]"

    - name: Run tests with pytest
      run: |
        pytest